modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="patchesandbeyond"
version="0.3"
displayName="Patches and Beyond"
authors="UnderscoreKilburn"
description="A set of bugfix patches for several mods included in Create: Above and Beyond."

[[dependencies.patchesandbeyond]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.patchesandbeyond]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
